function [hFig, hAx] = plot_roc_for_3h(ROC)
	
	figWidth = 340;
	figHeight = 240;
	pLength = 175;
	axGap = 5;

	flowColor = [0.07,0.39,0.50];
	nhaColor = [0.76,0.0,0.2];
	plvadColor = [0.87,0.50,0.13];
	diagCol = [0 0 0 0.7];
	diagCol = [0 0 0];
	curveCol = flowColor;

	[hFig, hAx] = init_figure(figWidth, figHeight, pLength);
	[hXAx, hYAx] = make_ax_offset(hFig, hAx, axGap);
	
	add_annotation(hXAx, hYAx);
	plot(hAx, ROC.X{1},ROC.Y{1}, ...
		'LineWidth',1.5,...
		'Color',curveCol);
	
	area(hAx, ROC.X{1}(:,1), ROC.Y{1}(:,1), ...
		'FaceColor',curveCol,...[.5 .5 .5],...[0.857,0.50,0.13],...plvadColor,...
		'EdgeColor','none', ...
		'FaceAlpha',0.04, ...
		'HandleVisibility','Off');

	plot(hAx, [0,1], [0,1], ...
		'LineWidth',1,...
		'LineStyle',':',...
		'Color',diagCol);
			
	text(0.6,0.3,sprintf('AUC = %1.2f',ROC.AUC{1}),'FontSize',9,'FontName','arial')

	
function [hFig, hAx] = init_figure(figWidth, figHeight, pLength)
	
	hFig = figure(...
		'Name','ROC curves per balloon level',...
	    'Position',[150,150,figWidth,figHeight],...
		'PaperUnits','centimeters',...
		'PaperSize',[19,19*(figHeight/figWidth)]...
		);

	hAx = axes(hFig,...
		'NextPlot','add',...
		'FontSize',9, ...
		'LineWidth',1, ...
		'XTick',0:0.2:1, ...
		'YTick',0:0.2:1, ...
		'XTickLabel',{'0','0.2','0.4','0.6','0.8','1'},...
		'YTickLabel',{'0','0.2','0.4','0.6','0.8','1'},...
		'XTickLabelRotation',0, ...
		'YTickLabelRotation',0, ...
		'GridColor',[0 0 0], ...
		'GridAlpha',0.22, ...
		'GridLineStyle',':', ...
		'XGrid','on', ...
		'YGrid','on', ...
		'TickDir','out',...
		'TickLength',[0.025,0], ...
		'Units','pixels', ...
		'Position',[50 50 pLength pLength] ...
		);

function [hXAx,hYAx] = make_ax_offset(hFig, hAx, gap)
	
	hYAx = copyobj(hAx, hFig);
	hXAx = copyobj(hAx, hFig);
	
	hAx.XAxis.Color = 'none';
	hAx.YAxis.Color = 'none';
	set(hAx, 'XTick',.2:.2:.8, 'YTick',.2:.2:.8);
	
	hXAx.Position(2) = hXAx.Position(2)-gap;
	set([hXAx;hYAx], ...
		'LineWidth',hAx.LineWidth,...
		'Color','none', ...
		'YGrid','off',...
		'XGrid','off')
	set(hXAx.YAxis, 'Color','none')
	
	hYAx.Position(1) = hYAx.Position(1)-gap;
	set(hYAx.XAxis, 'Color','none')

function add_annotation(hXAx, hYAx)
	hXLab = xlabel(hXAx, '1 - specificity', 'FontSize',9, 'FontName','Arial', 'Units', 'pixels');
	hYLab = ylabel(hYAx, 'sensitivity', 'FontSize',9, 'FontName','Arial', 'Units', 'pixels');
	hXLab.Position(2) = hXLab.Position(2)-4;
	hYLab.Position(1) = hYLab.Position(1)-5;
