function h_ax = add_subtitles(h_ax,subTitles,panelLength,yGap,spec)
	
	for j=1:size(h_ax,2)
		titBoxPos = [
			h_ax(1,j).Position(1)
			h_ax(1,j).Position(2)+panelLength+yGap/2
			panelLength
			22]';
		annotation('textbox',[0,0.5,0.2,0.1],...
			spec.titBox{:},...
			'Position',titBoxPos,...
			'FontWeight','bold',...
			'String',subTitles{j} ...
			);
	end
end