%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Data\IVS\Didrik\IV2_Seq3 - Water simulated HVAD thrombosis - Pre-pump - Pilot\Recorded\PowerLab\IV2_Seq3 - B1.txt
%
% Auto-generated by MATLAB on 19-Mar-2020 17:27:52

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [10, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ExcelDate", "Trykk1", "Trykk2", "SensorAAccX", "SensorAAccY", "SensorAAccZ", "SensorBAccX", "SensorBAccY", "SensorBAccZ", "SensorAGyrX", "SensorAGyrY", "SensorAGyrZ"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
IV2Seq3B1 = readtable("C:\Data\IVS\Didrik\IV2_Seq3 - Water simulated HVAD thrombosis - Pre-pump - Pilot\Recorded\PowerLab\IV2_Seq3 - B1.txt", opts);


%% Clear temporary variables
clear opts