%% Add dropdown list to current figure

h_button=uicontrol('Parent',gcf,'Style','listbox',...
    'ListboxTop',1,...
    'String',{sub2_y_varname,sub2_yy_varname},...
    'Units','normalized'...
    );
