function specs = get_specs_for_plot_NHA

	% Import color palettes
	Colors_IV2
	
	specs.fig = {
		'Color',[1,1,1]
		}; 
	specs.speedMarkers = {'o','diamond','square','hexagram'};%'pentagram'};
	specs.backPtsSize = 10;
	specs.backPts = {specs.backPtsSize,...
		'MarkerEdgeAlpha',0.6,...
		'MarkerFaceAlpha',0.6};
	specs.line= {...
		'MarkerSize',6,...
		'LineStyle','-',...
		'LineWidth',1.8};
	specs.ax = {...
		'LineWidth',2,...
		'FontSize',12,...
		'FontName','Gill Sans Nova',...
		'Color',[.965 .965 .965],...
		'YGrid','on',...
		'XGrid','on',...
		'GridLineStyle','-',...
		'GridColor',[1,1,1],...
		'GridAlpha',1,...
		'ColorOrder',Colors.Fig.Cats.Speeds4
		};
	specs.rocAx = {...
		...'Color',[1 1 1],...
		...'GridColor',[0.96,0.96,0.96],...
		'Color',[.965 .965 .965],...
		'GridColor',[1,1,1],...
		'GridLineStyle','-',...
		'GridAlpha',1,...
		'box','off'
		};
	specs.axTick = {
		'TickDirection', 'out',...
		'TickLength',[0.02,0.025]
		};
	specs.subPlt = {
		'ColorOrder',Colors.Fig.Cats.Speeds4
		};
	specs.text = {
		'LineWidth',1.5,...
		'FontSize',11,...
		'FontName','Gill Sans Nova',...
		};
	specs.subTit = {
		'FontWeight','normal',...
		...'FontWeight','bold',...
		'FontSize',12
		};
	specs.leg = {
		'Box','off',...
		'Location','southeastoutside',...
		'FontName','Gill Sans Nova',...
		'FontSize',12,...
		'FontWeight','normal'
		};
	specs.legTit = {
		'FontWeight','normal',...
		'FontName','Gill Sans Nova',...
		};
	specs.supTit = {
		'FontName','Gill Sans Nova',...
		'FontSize',16
		};
	specs.supXLab = {
		'FontSize',14,...
		'FontName','Gill Sans Nova',...
		'FontWeight','bold'
		};
	