function specs = get_specs_for_plot_NHA

	% Import color palettes
	Colors_IV2
	
	specs.fig = {
		'Color',[1,1,1]
		};
	specs.speedMarkers = {'o','diamond','square','hexagram'};%'pentagram'};
	specs.backPtsSize = 11;
	specs.backPts = {specs.backPtsSize,...
		'MarkerEdgeAlpha',0.6,...
		'MarkerFaceAlpha',0.6};
	specs.backLines = {
		'LineWidth',0.5 ...
		};
	specs.line= {...
		'MarkerSize',6,...
		'LineStyle','-',...
		'LineWidth',1.85};
	specs.ax = {...
		'LineWidth',2,...
		'FontSize',13,...
		'FontName','Gill Sans Nova',...
		'GridColor',[1,1,1],...
		'Color',[.97 .97 .97],...
 		...'Color','none',...
 		...'GridColor',[0.95,0.95,0.95],...
		'YGrid','on',...
		'XGrid','on',...
		'GridLineStyle','-',...
		'GridAlpha',1,...
		'ColorOrder',Colors.Fig.Cats.Speeds4
		};
	specs.rocAx = {...
		'LineWidth',2,...
		'FontSize',14,...
		'FontName','Gill Sans Nova',...
		'GridColor',[.925 .925 .925],...
		'GridColor',[.95 .95 .95],...
		'Color',[1 1 1],...
		'GridColor',[1,1,1],...
		...'Color',[.97 .97 .97],...
		'YGrid','on',...
		'XGrid','on',...
		'GridLineStyle','-',...
		'GridAlpha',1,...
		'box','on',...
		'ColorOrder',Colors.Fig.Cats.Components4
		};
	specs.effIntervAx = {
		'LineWidth',3,...
		'FontSize',14,...
		'FontName','Gill Sans Nova',...
		'Color',[.965 .965 .965],...
		'YGrid','on',...
		'XGrid','off',...
		'GridLineStyle','-',...
		'GridColor',[1,1,1],...
		'GridAlpha',1};
	specs.rocDiag = {
		'LineStyle','-',...
		'Color',[0.8906,0.1016,0.1094,0.5],...
		...'Color',[.5 .5 .5],...
		'LineWidth',1 ...
		};
	specs.axTick = {
		'TickDirection', 'out',...
		'TickLength',[0.025,0.025]
		};
	specs.subPlt = {
		'ColorOrder',Colors.Fig.Cats.Speeds4
		};
	specs.text = {
		'LineWidth',1.5,...
		'FontSize',14,...
		'FontName','Gill Sans Nova',...
		};
	specs.subTit = {
		...'FontWeight','normal',...
		'FontWeight','bold',...
		'FontSize',14
		};
	specs.leg = {
		'Box','off',...
		'Location','southeastoutside',...
		'FontName','Gill Sans Nova',...
		'FontSize',14,...
		'FontWeight','normal'
		};
	specs.legTit = {
		'FontWeight','normal',...
		'FontName','Gill Sans Nova',...
		};
	specs.supTit = {
		'FontName','Gill Sans Nova',...
		'FontSize',16
		};
	specs.supXLab = {
		'FontSize',14,...
		'FontName','Gill Sans Nova',...
		...'FontWeight','bold'...
		'FontWeight','normal'
		};
	