function adjust_ax_format(hSub, hYAx)
	set(hSub,...
		'TickDir','out',...
		'TickLength',[.015 .015],...
		'Color',[.965 .965 .965],...
		'FontSize',9,...
		'XTickLabelRotation',55,...
		'FontName','Arial',...
		'LineWidth',1.1 ...
		);
	hSub(1).XAxis.TickLength = [.0 .0];

	set(hYAx,...
		'TickDir','out',...
		'TickLength',[.015 .015],...
		'FontName','Arial',...
		'LineWidth',1.1 ...
		);
	hSub(1).XAxis.TickLength = [.0 .0];
	
 	hYAx(1).YTick = hSub(1,1).YTick;
 	hYAx(2).YTick = hSub(2,1).YTick;
 	hYAx(1).YLim = hSub(1,1).YLim;
	hYAx(2).YLim = hSub(2,1).YLim;
		
	