function adjust_ax_format(hSub)
	set(hSub,...
		'TickDir','out',...
		'TickLength',[.017 .017],...
		'Color',[.965 .965 .965],...
		'FontSize',9,...
		'FontName','Arial',...
		'LineWidth',1.1 ...
		);
	hSub(1).XAxis.TickLength = [.0 .0];
	