function plot_specs = get_plot_specs
	% TODO: Implement return of which plot type on request by user input
	
	% Import color palettes
	Colors_IV2
	
	fontSize = 17; 
	fontName = 'Helvetica';%'Gill Sans Nova';%'Arial';%;

	plot_specs.fig = {
		'Color',[1,1,1]
		};
	plot_specs.speedMarkers = {'o','diamond','square','hexagram'};%'pentagram'};
	plot_specs.backPtsSize = 12;
	plot_specs.backPts = {plot_specs.backPtsSize,...
		'MarkerEdgeAlpha',0.65,...
		'MarkerFaceAlpha',0.65};
	plot_specs.backLines = {
		'LineWidth',1.1 ...
		};
	plot_specs.line= {...
		'MarkerSize',6,...
		'LineStyle','-',...
		'LineWidth',2.0};
	plot_specs.ax = {...
		'LineWidth',2,...
		'FontSize',fontSize,...
		'FontName',fontName,...
		...'GridColor',[0.95,0.95,0.95],...
		...'Color',[1 1 1],...
 		'GridColor',[1,1,1],...
		'Color',[.97 .97 .97],...
 		'YGrid','on',...
		'XGrid','on',...
		'GridLineStyle','-',...
		'GridAlpha',1,...
		...'TickLabelRotation',0,...
		'ColorOrder',Colors.Fig.Cats.Speeds4
		};
	plot_specs.rocAx = {...
		'LineWidth',2,...
		'FontSize',14,...
		'FontName',fontName,...
		'GridColor',[.925 .925 .925],...
		'GridColor',[.96 .96 .96],...
		...'GridColor',[1,1,1],...
		'Color',[1 1 1],...
		...'Color',[.97 .97 .97],...
		'YGrid','on',...
		'XGrid','on',...
		'GridLineStyle','-',...
		'GridAlpha',1,...
		'box','on',...
		'ColorOrder',Colors.Fig.Cats.Components4
		};
	plot_specs.rocSubTit = {
		'FontSize',fontSize,...
		'FontName',fontName,...
		'FontWeight','bold'
	};
	plot_specs.rocDiag = {
		'LineStyle','-',...
		'Color',[0.8906,0.1016,0.1094,0.5],...
		'Color',[0 0 0],...
		'Color',[.7 .7 .7],...
		'LineWidth',1.1 ...
		};
	plot_specs.axTick = {
		'TickDirection', 'out',...
		'TickLength',[0.025,0.025] ...
		};
	plot_specs.subPlt = {
		'ColorOrder',Colors.Fig.Cats.Speeds4,...
		'Units','points',...
		'Nextplot','add' ...
		};
	plot_specs.titBox = {
		...'BackgroundColor',[0.97,0.97,0.97], ...
		'BackgroundColor',[1 1 1], ...
		'HorizontalAlignment','center',...
		'Units','points',...
		'VerticalAlignment','baseline',...
		'FontSize',fontSize,...
		'FontName',fontName,...
		'FontWeight','normal',...
		'Margin',4,...
		'EdgeColor','none'...
		};
	plot_specs.sepBox = {
		...'BackgroundColor',[0.95,0.95,0.95], ...
		'BackgroundColor',[1 1 1], ...
		'Units','points',...
		'EdgeColor','none'
		};
	plot_specs.text = {
		'LineWidth',1.5,...
		'FontSize',fontSize,...
		'FontName',fontName,...
		};
	plot_specs.rocText = {
		'LineWidth',1.5,...
		'FontSize',fontSize,...
		'FontName',fontName,...
		};
	
	plot_specs.subTit = {
		'Units','points',...
		'FontWeight','normal',...
		...'FontWeight','bold',...
		'FontSize',fontSize,...
		'FontName',fontName ...
		};
	plot_specs.leg = {
		'Box','off',...
		'Location','southeastoutside',...
		'FontName',fontName,...
		'FontSize',fontSize,...
		'FontWeight','normal'
		};
	plot_specs.legTit = {
		'FontWeight','normal',...
		'FontName',fontName,...
		};
	plot_specs.supTit = {
		'FontName',fontName,...
		'FontSize',fontSize+2
		};
	plot_specs.supXLab = {
		'FontSize',fontSize,...
		'FontName',fontName,...
		'FontWeight','normal'
		};
	plot_specs.effIntervAx = {
		'LineWidth',3,...
		'FontSize',fontSize,...
		'FontName',fontName,...
		'Color',[.965 .965 .965],...
		'YGrid','on',...
		'XGrid','off',...
		'GridLineStyle','-',...
		'GridColor',[1,1,1],...
		'GridAlpha',1};
	
	% For sequence parts plot of spectrogram and time domain curves
	% -------------------------------------------------------------
	plot_specs.sequence_parts.leg_yGap = 0.005;
    plot_specs.sequence_parts.leg_xPos = 0.85;
    plot_specs.sequence_parts.yLab_xPos = -0.058;
    plot_specs.sequence_parts.yyLab_xPos = 1.039;
    plot_specs.sequence_parts.baseline_title = {
        'Units','data',...
        'HorizontalAlignment','center',...
        'FontSize',11,...
        'FontWeight','bold'};
    plot_specs.sequence_parts.event_bar = {
        'LineStyle','-',...
        'LineWidth',7,...
        'Marker','none',...
        'Color', [.85 .85 .85]};
    plot_specs.sequence_parts.bal_lev_bar = {
        'LineStyle','-',...
        'LineWidth',7,...
        'Marker','none',...
        'Color', [0.96,0.68,0.68]};
    plot_specs.sequence_parts.trans_lev_bar = {
        'LineStyle',':',...
        'LineWidth',1.5,...
        'Marker','none',...
        'Color', [.7 .7 .7]};
    plot_specs.sequence_parts.leg = {
        'EdgeColor','none',...
        'Box','off',...
        'FontSize',11};
    plot_specs.sequence_parts.leg_title = {
        'FontSize',11};
    plot_specs.sequence_parts.yLab = {
        'Interpreter','tex',...
        'Units','normalized',...
        'FontSize',11};