function Plot_Flag_Lines(time,plot_flags)
    
    for j=1:numel(plot_flags)
        h_xl = xline(gca,sudo.rel_time(sudo.flag==plot_flags(j)),...
            'LineStyle','--',...
            'LineWidth',1,...
            'Label',num2str(plot_flags(j)),...
            'LabelHorizontalAlignment','left',...
            'FontWeight','bold',...
            'DisplayName','Flag');
    end
    h_leg.String = h_leg.String(1:end-numel(plot_flags)+1);