function h = intervention_boxplot(...
		F, levs, vars, accAsdB, saveFig, Config)
	
	group = make_intervention_groups(F, levs);
	sPath = fullfile(Config.fig_path,'Boxplot');
	for i=1:size(vars,1)
		h = plot_intervention_boxes(...
			accAsdB, F, vars{i,1}, group, vars{i,2}, vars{i,3});
		if saveFig
			levStr = make_level_sting_for_save_name(levs);
			fileName = ['Boxplot - ',vars{i,2},' - ',levStr];
			save_figure(h, sPath, fileName, 300);
		end
	end

function hFig = plot_intervention_boxes(accAsdB, F, var, groups, varLab, ylims)

	specs = get_plot_specs;
	Colors_IV2

	% Used for converting accelerometer band powers into dB
	y = convert_bandpower_to_decibel(accAsdB, var, F);

	hFig = figure('Position',[380.5,222,800,800]);
	axes('Position',[0.15,0.20,0.65,0.75]);
	refGrp = groups;
	refGrp(contains(string(refGrp),{'Lev 1-4','Graft clamp'})) = missing;
	boxchart(refGrp, y, ...
		'Notch','on',...
		'BoxWidth',0.55,...
		'LineWidth',1.25 ,...
		'BoxFaceColor',[0 0 0],...
		'MarkerColor',[0 0 0] ...
		...'BoxFaceColor',[0.0052  0.0982  0.3498],...
		...'MarkerColor',[0.0052  0.0982  0.3498]...
		);
	hold on
	balGrp = groups;
	balGrp(not(contains(string(balGrp),'Lev 1-4'))) = missing;
	boxchart(balGrp, y, ...
		'Notch','on',...
		'BoxWidth',0.55,...
		'LineWidth',1.25 ,...
		'BoxFaceAlpha',0.8 ,...
		'BoxFaceColor',[0.8255    0.5777    0.2642],...
		'MarkerColor',[0.8255    0.5777    0.2642]...
		);
	clampGrp = groups;
	clampGrp(not(contains(string(clampGrp),'Graft clamp'))) = missing;
	boxchart(clampGrp, y, ...
		'Notch','on',...
		'BoxWidth',0.55,...
		'LineWidth',1.25 ,...
		'BoxFaceAlpha',0.8 ,...
		'BoxFaceColor',[0.0052    0.0982    0.3498] ,...
		'MarkerColor',[0.0052    0.0982    0.3498]...
		);

	h_ax = gca;
	set(h_ax, specs.ax{:},...
		'Color',[.97 .97 .97],...
		'GridColor',[.97 .97 .97],...
		'Color',[1 1 1],...
		'ColorOrder',Colors.Fig.Cats.Intervention5, ...
		'GridColor',[1 1 1]...
		)
	title(varLab, specs.supTit{:})

	hYLab = ylabel(varLab,specs.supXLab{:});
	hYLab.Position(1) = hYLab.Position(1)-20;

	if not(isempty(ylims)), ylim(ylims); end

