function add_titles_and_labels(hFig)
	annotation(hFig,'textbox',...
		[0.1 0.87 0.265 0.050],...
		'String',{'Clamp control interventions'},...
		'HorizontalAlignment','center',...
		'FontSize',16,...
		'FontName','Arial',...
		'EdgeColor','none',...
		'FitBoxToText','off');
	annotation(hFig,'textbox',...
		[0.365 0.87 0.4358 0.050],...
		'String',{'Balloon interventions'},...
		'HorizontalAlignment','center',...
		'FontSize',16,...
		'FontName','Arial',...
		'EdgeColor','none',...
		'FitBoxToText','off');
	annotation(hFig,'textbox',...
		[0.1 0.015 0.265 0.050],...
		'String',{'flow reduction levels'},...
		'HorizontalAlignment','center',...
		'FontSize',16,...
		'FontName','Arial',...
		'EdgeColor','none',...
		'FitBoxToText','off');
	annotation(hFig,'textbox',...
		[0.365 0.015 0.4358 0.050],...
		'String',{'areal obstruction levels'},...
		'HorizontalAlignment','center',...
		'FontSize',16,...
		'FontName','Arial',...
		'EdgeColor','none',...
		'FitBoxToText','off');